# Generated by Django on 2025-10-23
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('verified', models.BooleanField(default=False)),
                ('funded_recently', models.BooleanField(default=False)),
                ('sponsors_count', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['location'], name='communities_location_idx'),
        ),
    ]
