# Generated by Django on 2025-10-23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_seed_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='community',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='community',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contribution_type', models.CharField(choices=[('cash', 'Cash'), ('kind', 'In-Kind'), ('grant', 'Grant')], default='cash', max_length=16)),
                ('date', models.DateField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='communities.community')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='communities.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communities.community')),
            ],
            options={'ordering': ['-date']},
        ),
    ]
